public class SimulateFrame extends javax.swing.JFrame {
    
    public SimulateFrame() {
        initComponents();
    }

    public double getReading() {
        return sliderSensor.getValue() / 100.0;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sliderSensor = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sensor value:");

        sliderSensor.setMajorTickSpacing(10);
        sliderSensor.setMinorTickSpacing(1);
        sliderSensor.setPaintLabels(true);
        sliderSensor.setPaintTicks(true);
        sliderSensor.setValue(0);
        sliderSensor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sliderSensorKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliderSensor, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderSensor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sliderSensorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sliderSensorKeyPressed
        String press = String.valueOf(evt.getKeyChar());
        int num;
        try {
            num = Integer.parseInt(press) * 10;
            if (num == 0) {
                num = 100;
            }
            sliderSensor.setValue(num);
        } catch (Exception e) {
            if (press.equals("`")) {
                num = 0;
                sliderSensor.setValue(num);
            }
        }
    }//GEN-LAST:event_sliderSensorKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSlider sliderSensor;
    // End of variables declaration//GEN-END:variables
}
